-- Local development seed (runs on `npx supabase db reset`). Never applied to production.
-- Brand dictionary (full name/spelling → short form for the Excel product name), agreed 2026-10-06.
-- Production has the same entries; keep the two in sync when brands are added on the brand screen.
insert into public.brand_dictionary (full_name, short_form) values
  ('지포어', 'G/F'),
  ('지포', 'G/F'),
  ('지포*', 'G/F'),
  ('G / F', 'G/F'),
  ('G/F', 'G/F'),
  ('G/FORE', 'G/F'),
  ('GFORE', 'G/F'),
  ('ㅈㅍㅇ', 'G/F'),
  ('PXG', 'pxg'),
  ('피엑스지', 'pxg'),
  ('PX*', 'pxg'),
  ('px', 'pxg'),
  ('말본', '말'),
  ('MALBON', '말'),
  ('말*', '말'),
  ('말', '말'),
  ('사우스케이프', '사우스'),
  ('사우스', '사우스'),
  ('샤우스케이프', '사우스'),
  ('SC', '사우스'),
  ('SOUTH CAPE', '사우스'),
  ('사', '사우스'),
  ('타이틀리스트', '타이틀'),
  ('Titleist', '타이틀'),
  ('타이틀', '타이틀'),
  ('타', '타이틀'),
  ('A.P.C. Golf', '아페쎄'),
  ('A.P.C GOLF', '아페쎄'),
  ('아페쎄 골프', '아페쎄'),
  ('아페쎄', '아페쎄'),
  ('어메이징크리', 'AMZ'),
  ('어메이징크', 'AMZ'),
  ('어메이징', 'AMZ'),
  ('AMAZING', 'AMZ'),
  ('AMAZINGCRE', 'AMZ'),
  ('AMAZI**', 'AMZ'),
  ('세인트앤드류스', '세인트'),
  ('세인트 앤드**', '세인트'),
  ('St ANDREWS', '세인트'),
  ('마스터바니', '바니'),
  ('마스터**', '바니'),
  ('MASTER BUNNY EDITION', '바니'),
  ('MASTER BUNNY', '바니'),
  ('왁', '왁'),
  ('WAAC', '왁'),
  ('롤렉스', '로렉스'),
  ('로렉스', '로렉스'),
  ('ROLEX', '로렉스'),
  ('미우미우', '미우미우'),
  ('MIU MIU', '미우미우'),
  ('비비안웨스트우드', '비비안'),
  ('비비안 웨스트우드', '비비안'),
  ('Vivienne Westwood', '비비안'),
  ('톰브라운', '톰브'),
  ('톰 브라운', '톰브'),
  ('THOM BROWNE', '톰브'),
  ('버버리', '버버리'),
  ('BURBERRY', '버버리'),
  ('브루넬로 쿠치넬리', 'BC'),
  ('브루넬로쿠치넬리', 'BC'),
  ('Brunello Cucinelli', 'BC'),
  ('BC', 'BC'),
  ('제냐', '제냐'),
  ('ZEGNA', '제냐'),
  ('투미', '투미'),
  ('TUMI', '투미'),
  ('톰포드', '톰포드'),
  ('톰 포드', '톰포드'),
  ('TOM FORD', '톰포드'),
  ('몽클', '몽클'),
  ('몽클레르', '몽클'),
  ('MONCLER', '몽클');
